stages:
  - build
  - release
  - sonar
  - cleanup

image: maven:latest

cache:
  paths:
    - ~/.m2/repository
  policy: pull

before_script:
  - apt update

#.mvn-template: &mvn-definition
#  variables:
#    MAVEN_OPTS: -Dmaven.repo.local=/cache/maven.repository
#  image: maven:latest

build-job:
  stage: build
  script:
    - echo "Building project"
    - mvn -version
    - java -version
    - mvn clean package
    - apt-get install -y zip
    - mkdir binary
    - zip -r ./binary/beryllium-${CI_COMMIT_TAG}.zip target/*.jar src/ pom.xml README.md
    - chmod 777 ./binary/beryllium-${CI_COMMIT_TAG}.zip
  artifacts:
    paths:
      - target/*
      - binary/*
    expire_in: 1 day

release-job:
  stage: release
  dependencies:
    - build-job
#  image: registry.gitlab.com/gitlab-org/release-cli:latest

  script:
    - echo "Release to Gitlab releases"
    - echo "${CI_COMMIT_TAG}"
    - echo "${CI_PROJECT_ID}"
    - echo "${CI_JOB_TOKEN}"
    - echo "${CI_JOB_ID}"
    - ls ./binary
    - |
      curl --data "{
        \"tag_name\": \"${CI_COMMIT_TAG}\",
        \"name\": \"${CI_COMMIT_TAG}\",
        \"ref\": \"${CI_COMMIT_TAG}\",
        \"description\": \"## release n: ${CI_COMMIT_TAG}\",
        \"assets\": {}
        }" \
        --header "Content-Type: application/json" \
        --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
        --request POST "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/releases"
#    - |
#      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file beryllium-${CI_COMMIT_TAG}.zip "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/releases/${CI_COMMIT_TAG}"

#    - |
#      curl https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/releases/${CI_COMMIT_TAG}/beryllium-${CI_COMMIT_TAG}.zip --request POST --header "JOB-TOKEN: ${CI_JOB_TOKEN}" -F "file=@./beryllium-${CI_COMMIT_TAG}.zip"


